#!/usr/bin/with-contenv sh

LOGS_DIR="$(dirname "$LOG_FILE")"

# check if logs folder exists and create it
if [[ ! -d "$LOGS_DIR" ]]; then
  install -dm755 -o $PUID -g $PGID "$LOGS_DIR"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID /app/vaultwarden
