name: Delete Old Release Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete_old_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: List releases
        run: |
          for release in $(gh release list -L 100 | awk '{if(NR>1)print $1}'); do
            release_date=$(gh release view $release | grep "Created: " | awk '{print $2}')
            release_timestamp=$(date -d "$release_date" +%s)
            current_timestamp=$(date +%s)
            age_in_days=$(((current_timestamp - release_timestamp) / 86400))
            if [ $age_in_days -gt 7 ]; then
              echo "Deleting files in release $release (created $age_in_days days ago)"
              for file in $(gh release view $release --json name -q ".assets[].name" | jq -r .[]); do
                gh release delete $release --title $file
              done
            fi
          done