name: Merge dev into main

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm merge'
        required: true
      source_branch_name:
        description: 'Source branch to merge from'
        required: true
      target_branch_name:
        description: 'Target branch to merge into'
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge branches
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "yes" ]; then
            echo "Confirmation not provided, aborting merge."
            exit 1
          fi
          git checkout ${{ github.event.inputs.target_branch_name }}
          git merge --no-ff origin/${{ github.event.inputs.source_branch_name }}
          git push origin ${{ github.event.inputs.target_branch_name }}
